HW: 28
CIN: 16
SHAPE_1D: 428
FILTERS: 256
KERNEL_SIZE: 3
PADDING: 'same'
STRIDES: 1
POOL_STRIDES: 2
ENABLED: ['BF', 'MON', 'RT']
PARAMS:
    BF:
        eps: 0.5
DETAIL: True
TEST_CASES:
  - add_add
  - add_avgpool
  - add_concat
  - add_conv
  - add_convtrans
  - add_dense
  - add_dwconv
  - add_relu
  - add_reshape
  - avgpool_add
  - avgpool_avgpool
  - avgpool_concat
  - avgpool_conv
  - avgpool_convtrans
  - avgpool_dwconv
  - avgpool_relu
  - avgpool_reshape
  - concat_add
  - concat_avgpool
  - concat_concat
  - concat_conv
  - concat_convtrans
  - concat_dense
  - concat_dwconv
  - concat_relu
  - concat_reshape
  - conv_add
  - conv_avgpool
  - conv_concat
  - conv_conv
  - conv_convtrans
  - conv_dwconv
  - conv_hswish
  - conv_relu
  - conv_reshape
  - conv_se
  - convtrans_add
  - convtrans_avgpool
  - convtrans_concat
  - convtrans_conv
  - convtrans_convtrans
  - convtrans_dwconv
  - convtrans_relu
  - convtrans_reshape
  - dense_add
  - dense_concat
  - dense_dense
  - dense_relu
  - dwconv_add
  - dwconv_avgpool
  - dwconv_concat
  - dwconv_conv
  - dwconv_convtrans
  - dwconv_dwconv
  - dwconv_relu
  - dwconv_reshape
  - relu_add
  - relu_avgpool
  - relu_concat
  - relu_conv
  - relu_convtrans
  - relu_dense
  - relu_dwconv
  - relu_relu
  - relu_reshape
  - reshape_add
  - reshape_avgpool
  - reshape_concat
  - reshape_conv
  - reshape_convtrans
  - reshape_dwconv
  - reshape_relu
  - reshape_reshape
  - se_relu
