DETAIL: FALSE
IMPLEMENT: tensorflow
KERNELS:
  conv_bn_relu:
    INIT_SAMPLE_NUM: 10000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  dwconv_bn_relu:
    INIT_SAMPLE_NUM: 5000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  maxpool_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  avgpool_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  fc_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  concat_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  split_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  channel_shuffle:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  se_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  globalavgpool_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  bn_relu:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  bn_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  hswish_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  relu_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  add_relu:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  add_block:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
