DETAIL: FALSE
IMPLEMENT: tensorflow
BATCH_SIZE: 1
KERNELS:
  conv-bn-relu:
    INIT_SAMPLE_NUM: 10000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  dwconv-bn-relu:
    INIT_SAMPLE_NUM: 5000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  maxpool:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  avgpool:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  fc:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  concat:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  split:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  channelshuffle:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  se:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  global-avgpool:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  bnrelu:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  bn:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  hswish:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  relu:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  addrelu:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
  add:
    INIT_SAMPLE_NUM: 3000
    FINEGRAINED_SAMPLE_NUM: 20
    ITERATION: 3
    ERROR_THRESHOLD: 0.1
